"""followers

Revision ID: 337fd59f4f7f
Revises: d1085831d80d
Create Date: 2025-05-02 19:18:20.676253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337fd59f4f7f'
down_revision = 'd1085831d80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_requests',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requested_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requested_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('requester_id', 'requested_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('follow_requests')
    # ### end Alembic commands ###
