"""Add status column to Friend model

Revision ID: 770148c78244
Revises: 226172f0d8ea
Create Date: 2025-04-30 22:37:47.673710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770148c78244'
down_revision = '226172f0d8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
